import { useDeferredValue, useRef, useState } from 'react';
import type { FormEvent } from 'react';
import { File as FileIcon, FileText, Image as ImageIcon, Link as LinkIcon, Music, Search, SlidersHorizontal, Video } from 'lucide-react';
import { useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { UploadTray } from '../components/uploads/UploadTray';
import { ResourceKnowledgePanel } from '../components/resources/ResourceKnowledgePanel';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { ImpactDialog, type ImpactRequest } from '../components/ui/ImpactDialog';
import { CollectionGroup, ViewToolbar } from '../components/ui/ViewToolbar';
import { useCollectionView } from '../components/ui/useCollectionView';
import { type Note, type NoteInput, useNoteActions } from '../data/useNotes';
import { useOrganization } from '../data/useOrganization';
import { useProjects } from '../data/useProjects';
import { useImpactActions } from '../data/useImpacts';
import { type ResourceDetail, type ResourceSummary, useLinkActions, useResource, useResourceAccess, useResourceActions, useResources } from '../data/useResources';

export function Library() {
  const [viewMode, setViewMode] = useCollectionView('library', 'grid'); const [creating, setCreating] = useState<'choose' | 'note' | 'link' | null>(null); const [advancedOpen, setAdvancedOpen] = useState(false); const navigate = useNavigate(); const location = useLocation(); const resourceId = location.pathname.match(/^\/library\/([^/]+)$/)?.[1];
  const [searchParams, setSearchParams] = useSearchParams(); const query = searchParams.get('q') ?? ''; const deferredQuery = useDeferredValue(query); const type = searchParams.get('type') as 'note' | 'file' | 'link' | null; const status = searchParams.get('status') === 'archived' ? 'archived' : 'active'; const projectId = searchParams.get('projectId') ?? ''; const folderId = searchParams.get('folderId') ?? ''; const tag = searchParams.get('tag') ?? '';
  const resources = useResources({ query: deferredQuery || undefined, type: type ?? undefined, status, projectId: projectId || undefined, folderId: folderId || undefined, tag: tag || undefined }); const detail = useResource(resourceId); const noteActions = useNoteActions(); const linkActions = useLinkActions(); const projects = useProjects('active'); const organization = useOrganization(projectId || undefined); const items = resources.data?.pages.flatMap(page => page.data) ?? []; const projectItems = projects.data?.pages.flatMap(page => page.data) ?? []; const activeFilters = Boolean(query || type || status === 'archived' || projectId || folderId || tag); const advancedFilters = Boolean(projectId || folderId || tag);
  const setFilter = (name: string, value?: string) => { const next = new URLSearchParams(searchParams); if (value) next.set(name, value); else next.delete(name); if (name === 'projectId') next.delete('folderId'); setSearchParams(next, { replace: true }); };
  const setGroup = (group: 'all' | 'note' | 'file' | 'link' | 'archived') => { const next = new URLSearchParams(searchParams); next.delete('type'); next.delete('status'); if (group === 'archived') next.set('status', 'archived'); else if (group !== 'all') next.set('type', group); setSearchParams(next, { replace: true }); };
  const listDestination = `/library${searchParams.size ? `?${searchParams}` : ''}`;
  if (resourceId) { const selected = detail.data; return <main className="w-full px-4 py-7 md:px-8"><Button onClick={() => navigate(listDestination)}>← Biblioteca</Button>{detail.isPending && <p role="status" className="mt-5">Cargando recurso…</p>}{detail.isError && <p role="alert" className="mt-5 text-red-600">No se pudo abrir el recurso.</p>}{selected && <ResourceLifecycle resource={selected} onArchived={() => navigate(listDestination)}/>} {selected?.type === 'note' && <NoteEditor note={{ ...selected, currentVersion: { id: '', ordinal: 1, content: selected.content ?? '' } }} busy={noteActions.update.isPending} onCancel={() => navigate(listDestination)} onSave={async body => { const saved = await noteActions.update.mutateAsync({ id: selected.id, body }); return saved.contentUnchanged; }}/>} {selected?.type === 'file' && <FileResource resource={selected}/>} {selected?.type === 'link' && <LinkResource resource={selected}/>} {selected && <ResourceKnowledgePanel key={selected.id} resource={selected}/>}</main>; }
  return <main className="w-full px-4 pb-20 pt-7 md:px-8" aria-label="Biblioteca">
    <ViewToolbar viewMode={viewMode} setViewMode={setViewMode} onNew={() => setCreating('choose')} newLabel="Añadir recurso" groups={<><CollectionGroup active={!type && status === 'active'} onClick={() => setGroup('all')}>Todos</CollectionGroup><CollectionGroup active={type === 'note' && status === 'active'} onClick={() => setGroup('note')}>Notas</CollectionGroup><CollectionGroup active={type === 'file' && status === 'active'} onClick={() => setGroup('file')}>Archivos</CollectionGroup><CollectionGroup active={type === 'link' && status === 'active'} onClick={() => setGroup('link')}>Enlaces</CollectionGroup><CollectionGroup active={status === 'archived'} onClick={() => setGroup('archived')}>Archivados</CollectionGroup><button type="button" className="grid h-9 w-9 place-items-center rounded-md text-outline hover:bg-surface-variant focus-visible:outline-2 focus-visible:outline-primary" aria-label="Filtros avanzados" aria-expanded={advancedOpen} onClick={() => setAdvancedOpen(value => !value)}><SlidersHorizontal size={17}/></button></>} search={<label className="flex h-9 items-center gap-2 rounded-md bg-surface-variant px-3 text-outline focus-within:outline-2 focus-within:outline-primary"><Search size={16} aria-hidden="true"/><input type="search" value={query} onChange={event => setFilter('q', event.target.value)} placeholder="Buscar recursos" aria-label="Buscar recursos" className="min-w-0 flex-1 border-0 bg-transparent text-sm text-on-background outline-none placeholder:text-outline"/></label>} />
    {advancedOpen && <section className="mb-4 grid gap-3 rounded-lg bg-surface-variant/50 p-4 sm:grid-cols-3" aria-label="Filtros avanzados">
      <label className="text-sm text-outline">Proyecto<select className="mt-1 block h-9 w-full rounded-md border-0 bg-surface-variant px-2 text-on-background" value={projectId} onChange={event => setFilter('projectId', event.target.value)}><option value="">Todos</option>{projectItems.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label>
      <label className="text-sm text-outline">Carpeta<select className="mt-1 block h-9 w-full rounded-md border-0 bg-surface-variant px-2 text-on-background" value={folderId} disabled={!projectId || organization.isPending} onChange={event => setFilter('folderId', event.target.value)}><option value="">Todas</option>{organization.data?.folders.filter(folder => !folder.archivedAt).map(folder => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select></label>
      <label className="text-sm text-outline">Etiqueta<input className="mt-1 block h-9 w-full rounded-md border-0 bg-surface-variant px-2 text-on-background" value={tag} placeholder="tema/subtema" onChange={event => setFilter('tag', event.target.value.replace(/^#/, ''))}/></label>
      {projects.hasNextPage && <Button disabled={projects.isFetchingNextPage} onClick={() => projects.fetchNextPage()}>Cargar más proyectos</Button>}
    </section>}
    {advancedFilters && <div className="mb-4 flex flex-wrap items-center gap-1 text-xs text-outline" aria-label="Filtros activos">{projectId && <Button onClick={() => setFilter('projectId')}>Proyecto ×</Button>}{folderId && <Button onClick={() => setFilter('folderId')}>Carpeta ×</Button>}{tag && <Button onClick={() => setFilter('tag')}>#{tag} ×</Button>}<Button onClick={() => setSearchParams({}, { replace: true })}>Limpiar filtros</Button></div>}
    <UploadTray/>
    {resources.isPending && <p role="status" className="mt-6">Cargando Biblioteca…</p>}
    {resources.isFetching && !resources.isPending && <p className="mt-3 text-sm text-outline">Actualizando resultados…</p>}
    {resources.isError && <div role="alert" className="mt-6"><p className="text-red-600">No se pudo cargar la Biblioteca.</p><Button variant="outline" onClick={() => resources.refetch()}>Reintentar</Button></div>}
    {!resources.isPending && !resources.isError && items.length === 0 && (activeFilters ? <section className="mt-8 py-10 text-center"><h2 className="font-medium">No hay resultados</h2><p className="mt-1 text-sm text-outline">Prueba retirando uno o más filtros.</p><Button className="mt-4" onClick={() => setSearchParams({}, { replace: true })}>Limpiar filtros</Button></section> : <section className="mt-8 py-10 text-center"><FileText className="mx-auto text-outline" size={36}/><h2 className="mt-3 font-medium">Tu Biblioteca está vacía</h2><p className="mt-1 text-sm text-outline">Crea una nota, guarda un enlace o carga un archivo.</p><Button className="mt-4" onClick={() => setCreating('choose')}>Crear recurso</Button></section>)}
    {!resources.isPending && !resources.isError && <p className="mt-4 text-sm text-outline" aria-live="polite">{items.length}{resources.hasNextPage ? '+' : ''} {items.length === 1 ? 'resultado' : 'resultados'}</p>}
    {items.length > 0 && (viewMode === 'grid' ? <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{items.map(resource => <Card key={resource.id} title={resource.title} subtitle={resource.description || resource.mediaType || 'Nota'} icon={<ResourceIcon resource={resource} size={17}/>} preview={resource.previewImageUrl ? <img src={resource.previewImageUrl} alt="" loading="lazy" className="h-full w-full object-cover"/> : <ResourceIcon resource={resource} size={42}/>} onClick={() => navigate(`/library/${resource.id}${searchParams.size ? `?${searchParams}` : ''}`)}/>)}</div> : <div className="mt-4 divide-y divide-border/50">{items.map(resource => <button key={resource.id} className="flex w-full items-center gap-3 rounded-md px-2 py-3 text-left hover:bg-surface-variant focus-visible:outline-2 focus-visible:outline-primary" onClick={() => navigate(`/library/${resource.id}${searchParams.size ? `?${searchParams}` : ''}`)}><ResourceIcon resource={resource} size={18}/><span className="min-w-0 flex-1"><strong className="block truncate font-medium">{resource.title}</strong><small className="text-outline">{resource.description || resource.mediaType || 'Nota'} · {resource.status}</small></span><time className="text-xs text-outline">{new Date(resource.updatedAt).toLocaleDateString()}</time></button>)}</div>)}
    {resources.hasNextPage && <Button className="mt-5" variant="outline" onClick={() => resources.fetchNextPage()}>Cargar más</Button>}
    {creating && <div className="fixed inset-0 z-50 overflow-auto bg-background p-6">{creating === 'choose' && <section className="mx-auto mt-16 max-w-md"><h2 className="text-xl font-semibold">Añadir recurso</h2><div className="mt-5 grid gap-3"><Button onClick={() => setCreating('note')}>Crear nota</Button><Button onClick={() => setCreating('link')}>Guardar enlace web</Button><Button onClick={() => { setCreating(null); document.getElementById('library-upload-input')?.click(); }}>Subir archivo</Button><Button onClick={() => setCreating(null)}>Cancelar</Button></div></section>}{creating === 'note' && <NoteEditor busy={noteActions.create.isPending} onCancel={() => setCreating(null)} onSave={async body => { const saved = await noteActions.create.mutateAsync(body); setCreating(null); navigate(`/library/${saved.id}${searchParams.size ? `?${searchParams}` : ''}`); return false; }}/>} {creating === 'link' && <LinkEditor busy={linkActions.create.isPending} onCancel={() => setCreating(null)} onSave={async url => { const saved = await linkActions.create.mutateAsync({ url }); setCreating(null); navigate(`/library/${saved.id}${searchParams.size ? `?${searchParams}` : ''}`); }}/>}</div>}
  </main>;
}

function ResourceIcon({ resource, size }: { resource: ResourceSummary; size: number }) { if (resource.type === 'note') return <FileText size={size}/>; if (resource.type === 'link') return <LinkIcon size={size}/>; if (resource.mediaType?.startsWith('image/')) return <ImageIcon size={size}/>; if (resource.mediaType?.startsWith('audio/')) return <Music size={size}/>; if (resource.mediaType?.startsWith('video/')) return <Video size={size}/>; return <FileIcon size={size}/>; }

function ResourceLifecycle({ resource, onArchived }: { resource: ResourceDetail; onArchived: () => void }) {
  const [request, setRequest] = useState<ImpactRequest | null>(null); const actions = useImpactActions();
  return <section className="mt-5 flex items-center gap-2 rounded border border-border p-3" aria-label="Ciclo de vida del recurso">{resource.status === 'archived' ? <><p className="flex-1 text-sm">Este Recurso está archivado. Sus usos existentes conservan la misma identidad.</p><Button variant="primary" disabled={actions.restoreResource.isPending} onClick={() => actions.restoreResource.mutate(resource.id)}>Restaurar</Button></> : <><p className="flex-1 text-sm">Estas acciones afectan al Recurso canónico en toda tu Cuenta.</p><Button variant="outline" onClick={() => setRequest({ entityType: 'resource', id: resource.id, action: 'archive' })}>Archivar</Button><Button variant="outline" onClick={() => setRequest({ entityType: 'resource', id: resource.id, action: 'delete' })}>Eliminar</Button></>}{request && <ImpactDialog request={request} onClose={() => setRequest(null)} onDone={() => { setRequest(null); onArchived(); }}/>}</section>;
}

function FileResource({ resource }: { resource: ResourceDetail }) {
  const previewable = resource.mediaType === 'application/pdf' || resource.mediaType?.startsWith('image/'); const media = resource.mediaType?.startsWith('audio/') || resource.mediaType?.startsWith('video/'); const preview = useResourceAccess(resource.id, Boolean(previewable)); const actions = useResourceActions(); const [mediaUrl, setMediaUrl] = useState(''); const [previewError, setPreviewError] = useState(''); const [accessibility, setAccessibility] = useState(resource.accessibilityText ?? ''); const [message, setMessage] = useState('');
  const download = async () => { const value = await actions.access(resource.id, 'download'); window.open(value.url, '_blank', 'noopener,noreferrer'); };
  const loadMedia = async () => { try { setMediaUrl((await actions.access(resource.id, 'inline')).url); } catch { setPreviewError('No se pudo iniciar la reproducción. El original sigue disponible.'); } };
  return <article className="mx-auto mt-5 max-w-4xl"><div className="flex items-start gap-3"><ResourceIcon resource={resource} size={36}/><div className="flex-1"><h1 className="text-2xl font-semibold">{resource.title}</h1><p className="text-sm text-outline">{resource.mediaType} · {resource.byteSize == null ? 'Tamaño desconocido' : `${(resource.byteSize / 1024 / 1024).toFixed(1)} MiB`} · {resource.origin} · {resource.status}</p></div><Button variant="primary" onClick={() => void download()}>Descargar original</Button></div>
    <section className="mt-6 rounded-lg border border-border p-4" aria-label="Vista previa">{preview.isPending && <p role="status">Preparando vista previa…</p>}{preview.isError && <p role="alert">No se pudo mostrar la vista previa. Puedes descargar el original.</p>}{preview.data?.url && resource.mediaType?.startsWith('image/') && <img className="max-h-[65vh] max-w-full" src={preview.data.url} alt={resource.accessibilityText || resource.title} onError={() => setPreviewError('La imagen no pudo previsualizarse. El original sigue disponible.')}/>} {preview.data?.url && resource.mediaType === 'application/pdf' && <iframe className="h-[65vh] w-full" src={preview.data.url} title={`Vista previa de ${resource.title}`} onError={() => setPreviewError('El PDF no pudo previsualizarse. El original sigue disponible.')}/>} {media && !mediaUrl && <Button variant="outline" onClick={() => void loadMedia()}>Cargar reproductor</Button>}{mediaUrl && resource.mediaType?.startsWith('audio/') && <audio className="w-full" controls preload="none" src={mediaUrl}>Tu navegador no puede reproducir este audio.</audio>}{mediaUrl && resource.mediaType?.startsWith('video/') && <video className="max-h-[65vh] w-full" controls preload="none" src={mediaUrl}>Tu navegador no puede reproducir este video.</video>}{!previewable && !media && <p>No hay vista previa para este formato. El original está disponible para descarga.</p>}{previewError && <p role="alert" className="mt-2 text-red-600">{previewError}</p>}</section>
    {resource.accessibilityRequired && <section className="mt-6"><label className="block text-sm font-medium">Texto alternativo o descripción accesible{resource.accessibilityMissing && <span className="ml-2 text-red-600">Requerido</span>}<textarea className="mt-1 min-h-28 w-full rounded border border-border bg-background p-2" maxLength={2000} value={accessibility} onChange={event => setAccessibility(event.target.value)}/></label><Button className="mt-2" variant="primary" disabled={actions.accessibility.isPending} onClick={async () => { try { await actions.accessibility.mutateAsync({ id: resource.id, text: accessibility }); setMessage('Información de accesibilidad guardada.'); } catch { setMessage('No se pudo guardar.'); } }}>Guardar accesibilidad</Button>{message && <p role="status" className="mt-2">{message}</p>}</section>}
  </article>;
}

function LinkResource({ resource }: { resource: ResourceDetail }) {
  const actions = useLinkActions(); const [editing, setEditing] = useState(false); const [title, setTitle] = useState(resource.title); const [description, setDescription] = useState(resource.description ?? ''); const [message, setMessage] = useState('');
  const save = async (event: FormEvent) => { event.preventDefault(); try { await actions.update.mutateAsync({ id: resource.id, title, description }); setEditing(false); setMessage('Enlace actualizado.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo guardar.'); } };
  return <article className="mx-auto mt-5 max-w-3xl"><div className="flex items-start gap-3"><LinkIcon size={36}/><div className="min-w-0 flex-1"><h1 className="text-2xl font-semibold">{resource.title}</h1><a className="block truncate text-sm text-blue-600 underline" href={resource.url ?? '#'} target="_blank" rel="noopener noreferrer">{resource.url}</a></div><Button variant="outline" onClick={() => setEditing(value => !value)}>Editar</Button></div>{resource.previewImageUrl && <img className="mt-5 max-h-72 rounded border border-border" src={resource.previewImageUrl} alt=""/>}<p className="mt-4">{resource.description || 'Sin descripción.'}</p>{resource.metadataStatus === 'pending' && <p role="status" className="mt-3 text-sm text-outline">Obteniendo metadatos…</p>}{resource.metadataStatus === 'failed' && <div role="alert" className="mt-3"><p>No se pudieron obtener los metadatos. El enlace sigue guardado.</p><Button className="mt-2" variant="outline" disabled={actions.retry.isPending} onClick={async () => { try { await actions.retry.mutateAsync({ id: resource.id }); setMessage('Reintento iniciado.'); } catch { setMessage('No se pudo reintentar.'); } }}>Reintentar metadatos</Button></div>}{editing && <form className="mt-6 rounded border border-border p-4" onSubmit={save}><label className="block text-sm font-medium">Título<input className="mt-1 w-full rounded border border-border bg-background p-2" maxLength={160} value={title} onChange={event => setTitle(event.target.value)}/></label><label className="mt-4 block text-sm font-medium">Descripción<textarea className="mt-1 min-h-28 w-full rounded border border-border bg-background p-2" maxLength={1000} value={description} onChange={event => setDescription(event.target.value)}/></label><Button className="mt-3" type="submit" variant="primary" disabled={actions.update.isPending}>Guardar cambios</Button></form>}{message && <p role="status" className="mt-3">{message}</p>}</article>;
}

function LinkEditor({ busy, onCancel, onSave }: { busy: boolean; onCancel: () => void; onSave: (url: string) => Promise<void> }) {
  const [url, setUrl] = useState(''); const [message, setMessage] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); try { const parsed = new URL(url); if (!['http:', 'https:'].includes(parsed.protocol)) throw new Error(); await onSave(url); } catch (error) { setMessage(error instanceof Error && error.message ? error.message : 'Ingresa una URL HTTP o HTTPS válida.'); } };
  return <form className="mx-auto mt-16 max-w-xl" onSubmit={submit}><h2 className="text-xl font-semibold">Guardar enlace web</h2><label className="mt-5 block text-sm font-medium">Dirección web<input className="mt-1 w-full rounded border border-border bg-background p-2" type="url" placeholder="https://ejemplo.com" required value={url} onChange={event => setUrl(event.target.value)}/></label>{message && <p role="alert" className="mt-3 text-red-600">{message}</p>}<div className="mt-5 flex gap-2"><Button type="button" onClick={onCancel}>Cancelar</Button><Button type="submit" variant="primary" disabled={busy}>{busy ? 'Guardando…' : 'Guardar enlace'}</Button></div></form>;
}

function NoteEditor({ note, busy, onCancel, onSave }: { note?: Note; busy: boolean; onCancel: () => void; onSave: (input: NoteInput) => Promise<boolean | undefined> }) {
  const [title, setTitle] = useState(note?.title ?? ''); const [description, setDescription] = useState(note?.description ?? ''); const [content, setContent] = useState(note?.currentVersion.content ?? ''); const [message, setMessage] = useState('');
  const [linkQuery, setLinkQuery] = useState(''); const editor = useRef<HTMLTextAreaElement>(null); const matching = useResources({ query: linkQuery.trim() || undefined }, Boolean(linkQuery.trim()));
  const insertLink = (id: string, label: string) => { const position = editor.current?.selectionStart ?? content.length; const link = `[[resource:${id}|${label}]]`; setContent(current => current.slice(0, position) + link + current.slice(position)); setLinkQuery(''); requestAnimationFrame(() => { editor.current?.focus(); editor.current?.setSelectionRange(position + link.length, position + link.length); }); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!title.trim()) { setMessage('El título es obligatorio.'); return; } try { const unchanged = await onSave({ title, description, content }); setMessage(unchanged ? 'El contenido ya estaba actualizado.' : 'Nota guardada.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo guardar. Puedes reintentar.'); } };
  return <form className="mx-auto mt-4 max-w-3xl" onSubmit={submit}><label className="block text-sm font-medium">Título<input className="mt-1 w-full rounded border border-border bg-background p-2 text-xl" value={title} maxLength={160} onChange={event => setTitle(event.target.value)}/></label><label className="mt-4 block text-sm font-medium">Descripción<input className="mt-1 w-full rounded border border-border bg-background p-2" value={description} onChange={event => setDescription(event.target.value)}/></label><label className="mt-4 block text-sm font-medium">Contenido<textarea ref={editor} className="mt-1 min-h-80 w-full rounded border border-border bg-background p-3" value={content} onChange={event => setContent(event.target.value)}/></label><div className="mt-2 rounded border border-border p-3 text-sm"><label className="block">Insertar enlace a un recurso<input className="mt-1 w-full rounded border border-border bg-background p-2" value={linkQuery} onChange={event => setLinkQuery(event.target.value)} placeholder="Busca un título o alias" /></label><p className="mt-1 text-xs text-outline">También puedes escribir [[Título]] o [[Título#sección|texto]]. Los enlaces insertados desde el buscador mantienen la identidad aunque cambie el título.</p>{matching.isError && <p role="alert">No se pudo buscar recursos.</p>}{linkQuery.trim() && <ul className="mt-2 max-h-36 overflow-auto">{matching.data?.pages.flatMap(page => page.data).filter(item => item.id !== note?.id).map(item => <li key={item.id}><Button type="button" onClick={() => insertLink(item.id, item.title)}>Insertar {item.title}</Button></li>)}</ul>}</div>{message && <p role="status" className="mt-3 text-sm">{message}</p>}<div className="mt-5 flex gap-2"><Button type="button" onClick={onCancel}>Cancelar</Button><Button type="submit" variant="primary" disabled={busy}>{busy ? 'Guardando…' : 'Guardar'}</Button></div></form>;
}
