import { useDeferredValue, useRef, useState } from 'react';
import type { FormEvent } from 'react';
import { File as FileIcon, FileText, Folder, Image as ImageIcon, Link as LinkIcon, Music, Search, Video } from 'lucide-react';
import { useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { UploadTray } from '../components/uploads/UploadTray';
import { ResourceKnowledgePanel } from '../components/resources/ResourceKnowledgePanel';
import { Button } from '../components/ui/Button';
import { CollectionItem } from '../components/ui/CollectionItem';
import { Dialog } from '../components/ui/Dialog';
import { ConfirmDialog, NameDialog } from '../components/ui/NameDialog';
import { ImpactDialog, type ImpactRequest } from '../components/ui/ImpactDialog';
import { CollectionGroup, ViewToolbar } from '../components/ui/ViewToolbar';
import { useCollectionView } from '../components/ui/useCollectionView';
import { type Note, type NoteInput, useNoteActions } from '../data/useNotes';
import { type LibraryFolder, useLibraryFolderActions, useLibraryFolders } from '../data/useLibraryFolders';
import { useImpactActions } from '../data/useImpacts';
import { type ResourceDetail, type ResourceSummary, useLinkActions, useResource, useResourceAccess, useResourceActions, useResources } from '../data/useResources';

export function Library() {
  const [viewMode, setViewMode] = useCollectionView('library', 'grid');
  const [uploadOpen, setUploadOpen] = useState(false);
  const [impact, setImpact] = useState<ImpactRequest | null>(null);
  const [folderDialog, setFolderDialog] = useState<{ id?: string; name: string } | null>(null);
  const [deletingFolder, setDeletingFolder] = useState<LibraryFolder | null>(null);
  const [message, setMessage] = useState('');
  const navigate = useNavigate(); const location = useLocation();
  const resourceId = location.pathname.match(/^\/library\/([^/]+)$/)?.[1];
  const [searchParams, setSearchParams] = useSearchParams();
  const query = searchParams.get('q') ?? ''; const deferredQuery = useDeferredValue(query);
  const folderId = searchParams.get('libraryFolderId') ?? '';
  const status = searchParams.get('status') === 'archived' ? 'archived' : 'active';
  const folders = useLibraryFolders(); const folderActions = useLibraryFolderActions();
  const resources = useResources({ query: deferredQuery || undefined, type: 'file', status, libraryFolderId: folderId || 'root' });
  const detail = useResource(resourceId); const noteActions = useNoteActions();
  const items = resources.data?.pages.flatMap(page => page.data) ?? [];
  const folderItems = folders.data ?? [];
  const setFolder = (value: string) => { const next = new URLSearchParams(searchParams); if (value) next.set('libraryFolderId', value); else next.delete('libraryFolderId'); setSearchParams(next, { replace: true }); };
  const setStatus = (value: 'active' | 'archived') => { const next = new URLSearchParams(searchParams); if (value === 'archived') next.set('status', 'archived'); else next.delete('status'); setSearchParams(next, { replace: true }); };
  const setQuery = (value: string) => { const next = new URLSearchParams(searchParams); if (value) next.set('q', value); else next.delete('q'); setSearchParams(next, { replace: true }); };
  const move = async (id: string, destination: string | null) => { try { await folderActions.move.mutateAsync({ resourceIds: [id], folderId: destination }); setMessage('Archivo movido.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo mover el archivo.'); } };
  const dropResource = (event: React.DragEvent<HTMLElement>, destination: string | null) => { event.preventDefault(); const id = event.dataTransfer.getData('application/x-theke-resource'); if (id) void move(id, destination); };
  const resourceUrl = (id: string) => `/library/${id}${searchParams.size ? `?${searchParams}` : ''}`;
  const listDestination = `/library${searchParams.size ? `?${searchParams}` : ''}`;
  if (resourceId) { const selected = detail.data; return <main className="w-full px-4 py-7 md:px-8"><Button onClick={() => navigate(listDestination)}>← Biblioteca</Button>{detail.isPending && <p role="status" className="mt-5">Cargando recurso…</p>}{detail.isError && <p role="alert" className="mt-5 text-red-600">No se pudo abrir el recurso.</p>}{selected && <ResourceLifecycle resource={selected} onArchived={() => navigate(listDestination)}/>} {selected?.type === 'note' && <NoteEditor note={{ ...selected, currentVersion: { id: '', ordinal: 1, content: selected.content ?? '' } }} busy={noteActions.update.isPending} onCancel={() => navigate(listDestination)} onSave={async body => { const saved = await noteActions.update.mutateAsync({ id: selected.id, body }); return saved.contentUnchanged; }}/>} {selected?.type === 'file' && <FileResource resource={selected}/>} {selected?.type === 'link' && <LinkResource resource={selected}/>} {selected && <ResourceKnowledgePanel key={selected.id} resource={selected}/>}</main>; }
  return <main className="w-full px-4 pb-20 pt-7 md:px-8" aria-label="Biblioteca">
    <ViewToolbar viewMode={viewMode} setViewMode={setViewMode} onNew={() => setUploadOpen(true)} newLabel="Subir archivos" groups={<><CollectionGroup active={status === 'active'} onClick={() => setStatus('active')}>Archivos</CollectionGroup><CollectionGroup active={status === 'archived'} onClick={() => setStatus('archived')}>Archivados</CollectionGroup><button type="button" className="min-h-9 rounded-md px-3 text-sm text-outline hover:bg-surface-variant focus-visible:outline-2 focus-visible:outline-primary" onClick={() => setFolderDialog({ name: String() })}>Nueva carpeta</button></>} search={<label className="flex h-9 items-center gap-2 rounded-md bg-surface-variant px-3 text-outline focus-within:outline-2 focus-within:outline-primary"><Search size={16}/><input type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar archivos" aria-label="Buscar archivos" className="min-w-0 flex-1 border-0 bg-transparent text-sm text-on-background outline-none placeholder:text-outline"/></label>} />
    {folderId && <button type="button" className="mb-4 text-sm text-outline hover:underline focus-visible:outline-2 focus-visible:outline-primary" onClick={() => setFolder('')}>← Todas las carpetas</button>}
    {message && <p role="status" className="mb-3 text-sm text-outline">{message}</p>}
    {status === 'active' && folderItems.length > 0 && <div className={viewMode === 'grid' ? 'mb-6 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4' : 'mb-6'}>{folderItems.map(folder => <CollectionItem key={folder.id} view={viewMode} title={folder.name} detail="Carpeta" icon={<Folder size={18}/>} preview={<Folder size={44}/>} onOpen={() => setFolder(folder.id)} onDragOver={event => event.preventDefault()} onDrop={event => dropResource(event, folder.id)} actions={[{ label: 'Abrir', onSelect: () => setFolder(folder.id) }, { label: 'Renombrar', onSelect: () => setFolderDialog({ id: folder.id, name: folder.name }) }, { label: 'Eliminar carpeta', destructive: true, onSelect: () => setDeletingFolder(folder) }]} />)}</div>}
    {folderId && <div className="mb-3 rounded-md bg-surface-variant/50 p-3 text-sm text-outline" onDragOver={event => event.preventDefault()} onDrop={event => dropResource(event, null)}>Arrastra aquí para sacar un archivo de la carpeta</div>}
    {resources.isPending && <p role="status">Cargando archivos…</p>}
    {resources.isError && <div role="alert"><p>No se pudieron cargar los archivos.</p><Button onClick={() => resources.refetch()}>Reintentar</Button></div>}
    {!resources.isPending && !resources.isError && items.length === 0 && <div className="py-12 text-center text-sm text-outline"><FileIcon className="mx-auto mb-3" size={36}/><p>{query ? 'No hay resultados.' : folderId ? 'Esta carpeta está vacía.' : 'Aún no hay archivos.'}</p><Button className="mt-3" onClick={() => setUploadOpen(true)}>Subir archivos</Button></div>}
    {items.length > 0 && <div className={viewMode === 'grid' ? 'grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4' : ''}>{items.map(resource => <CollectionItem key={resource.id} view={viewMode} title={resource.title} detail={resource.mediaType ?? 'Archivo'} date={new Date(resource.updatedAt).toLocaleDateString()} icon={<ResourceIcon resource={resource} size={18}/>} preview={resource.previewImageUrl ? <img src={resource.previewImageUrl} alt="" className="h-full w-full object-cover" loading="lazy"/> : <ResourceIcon resource={resource} size={44}/>} onOpen={() => navigate(resourceUrl(resource.id))} onDragStart={event => { event.dataTransfer.setData('application/x-theke-resource', resource.id); event.dataTransfer.effectAllowed = 'move'; }} actions={[{ label: 'Abrir', onSelect: () => navigate(resourceUrl(resource.id)) }, ...folderItems.map(folder => ({ label: `Mover a ${folder.name}`, onSelect: () => void move(resource.id, folder.id) })), ...(resource.libraryFolderId ? [{ label: 'Mover fuera de carpeta', onSelect: () => void move(resource.id, null) }] : []), { label: 'Archivar', onSelect: () => setImpact({ entityType: 'resource', id: resource.id, action: 'archive' }) }, { label: 'Eliminar', destructive: true, onSelect: () => setImpact({ entityType: 'resource', id: resource.id, action: 'delete' }) }]} />)}</div>}
    {resources.hasNextPage && <Button className="mt-5" onClick={() => resources.fetchNextPage()}>Cargar más</Button>}
    {uploadOpen && <Dialog titleId="library-upload-title" onClose={() => setUploadOpen(false)} className="max-w-lg"><div className="flex items-center justify-between"><h2 id="library-upload-title" className="text-lg font-semibold">Subir archivos</h2><Button onClick={() => setUploadOpen(false)}>Cerrar</Button></div><UploadTray folderId={folderId || null}/></Dialog>}
    {impact && <ImpactDialog request={impact} onClose={() => setImpact(null)} onDone={() => setImpact(null)} />}
    {folderDialog && <NameDialog title={folderDialog.id ? 'Renombrar carpeta' : 'Crear carpeta'} initialValue={folderDialog.name} onClose={() => setFolderDialog(null)} onSave={async name => { if (folderDialog.id) await folderActions.rename.mutateAsync({ id: folderDialog.id, name }); else await folderActions.create.mutateAsync(name); setMessage(folderDialog.id ? 'Carpeta renombrada.' : 'Carpeta creada.'); }} />}
    {deletingFolder && <ConfirmDialog title={`Eliminar ${deletingFolder.name}`} description="Los archivos quedarán en la raíz de Biblioteca." onClose={() => setDeletingFolder(null)} onConfirm={async () => { await folderActions.remove.mutateAsync(deletingFolder.id); if (folderId === deletingFolder.id) setFolder(''); setMessage('Carpeta eliminada.'); }} />}
  </main>;
}

function ResourceIcon({ resource, size }: { resource: ResourceSummary; size: number }) { if (resource.type === 'note') return <FileText size={size}/>; if (resource.type === 'link') return <LinkIcon size={size}/>; if (resource.mediaType?.startsWith('image/')) return <ImageIcon size={size}/>; if (resource.mediaType?.startsWith('audio/')) return <Music size={size}/>; if (resource.mediaType?.startsWith('video/')) return <Video size={size}/>; return <FileIcon size={size}/>; }

function ResourceLifecycle({ resource, onArchived }: { resource: ResourceDetail; onArchived: () => void }) {
  const [request, setRequest] = useState<ImpactRequest | null>(null); const actions = useImpactActions();
  return <section className="mt-5 flex items-center gap-2 rounded-lg bg-surface-variant/55 p-3" aria-label="Ciclo de vida del recurso">{resource.status === 'archived' ? <><p className="flex-1 text-sm">Este Recurso está archivado. Sus usos existentes conservan la misma identidad.</p><Button variant="primary" disabled={actions.restoreResource.isPending} onClick={() => actions.restoreResource.mutate(resource.id)}>Restaurar</Button></> : <><p className="flex-1 text-sm">Estas acciones afectan al Recurso canónico en toda tu Cuenta.</p><Button variant="outline" onClick={() => setRequest({ entityType: 'resource', id: resource.id, action: 'archive' })}>Archivar</Button><Button variant="outline" onClick={() => setRequest({ entityType: 'resource', id: resource.id, action: 'delete' })}>Eliminar</Button></>}{request && <ImpactDialog request={request} onClose={() => setRequest(null)} onDone={() => { setRequest(null); onArchived(); }}/>}</section>;
}

function FileResource({ resource }: { resource: ResourceDetail }) {
  const previewable = resource.mediaType === 'application/pdf' || resource.mediaType?.startsWith('image/'); const media = resource.mediaType?.startsWith('audio/') || resource.mediaType?.startsWith('video/'); const preview = useResourceAccess(resource.id, Boolean(previewable)); const actions = useResourceActions(); const [mediaUrl, setMediaUrl] = useState(''); const [previewError, setPreviewError] = useState(''); const [accessibility, setAccessibility] = useState(resource.accessibilityText ?? ''); const [message, setMessage] = useState('');
  const download = async () => { const value = await actions.access(resource.id, 'download'); window.open(value.url, '_blank', 'noopener,noreferrer'); };
  const loadMedia = async () => { try { setMediaUrl((await actions.access(resource.id, 'inline')).url); } catch { setPreviewError('No se pudo iniciar la reproducción. El original sigue disponible.'); } };
  return <article className="mx-auto mt-5 max-w-4xl"><div className="flex items-start gap-3"><ResourceIcon resource={resource} size={36}/><div className="flex-1"><h1 className="text-2xl font-semibold">{resource.title}</h1><p className="text-sm text-outline">{resource.mediaType} · {resource.byteSize == null ? 'Tamaño desconocido' : `${(resource.byteSize / 1024 / 1024).toFixed(1)} MiB`} · {resource.origin} · {resource.status}</p></div><Button variant="primary" onClick={() => void download()}>Descargar original</Button></div>
    <section className="mt-6 rounded-lg bg-surface-variant/55 p-4" aria-label="Vista previa">{preview.isPending && <p role="status">Preparando vista previa…</p>}{preview.isError && <p role="alert">No se pudo mostrar la vista previa. Puedes descargar el original.</p>}{preview.data?.url && resource.mediaType?.startsWith('image/') && <img className="max-h-[65vh] max-w-full" src={preview.data.url} alt={resource.accessibilityText || resource.title} onError={() => setPreviewError('La imagen no pudo previsualizarse. El original sigue disponible.')}/>} {preview.data?.url && resource.mediaType === 'application/pdf' && <iframe className="h-[65vh] w-full" src={preview.data.url} title={`Vista previa de ${resource.title}`} onError={() => setPreviewError('El PDF no pudo previsualizarse. El original sigue disponible.')}/>} {media && !mediaUrl && <Button variant="outline" onClick={() => void loadMedia()}>Cargar reproductor</Button>}{mediaUrl && resource.mediaType?.startsWith('audio/') && <audio className="w-full" controls preload="none" src={mediaUrl}>Tu navegador no puede reproducir este audio.</audio>}{mediaUrl && resource.mediaType?.startsWith('video/') && <video className="max-h-[65vh] w-full" controls preload="none" src={mediaUrl}>Tu navegador no puede reproducir este video.</video>}{!previewable && !media && <p>No hay vista previa para este formato. El original está disponible para descarga.</p>}{previewError && <p role="alert" className="mt-2 text-red-600">{previewError}</p>}</section>
    {resource.accessibilityRequired && <section className="mt-6"><label className="block text-sm font-medium">Texto alternativo o descripción accesible{resource.accessibilityMissing && <span className="ml-2 text-red-600">Requerido</span>}<textarea className="mt-1 min-h-28 w-full rounded-md border-0 bg-surface-variant p-2 focus-visible:outline-2 focus-visible:outline-primary" maxLength={2000} value={accessibility} onChange={event => setAccessibility(event.target.value)}/></label><Button className="mt-2" variant="primary" disabled={actions.accessibility.isPending} onClick={async () => { try { await actions.accessibility.mutateAsync({ id: resource.id, text: accessibility }); setMessage('Información de accesibilidad guardada.'); } catch { setMessage('No se pudo guardar.'); } }}>Guardar accesibilidad</Button>{message && <p role="status" className="mt-2">{message}</p>}</section>}
  </article>;
}

function LinkResource({ resource }: { resource: ResourceDetail }) {
  const actions = useLinkActions(); const [editing, setEditing] = useState(false); const [title, setTitle] = useState(resource.title); const [description, setDescription] = useState(resource.description ?? ''); const [message, setMessage] = useState('');
  const save = async (event: FormEvent) => { event.preventDefault(); try { await actions.update.mutateAsync({ id: resource.id, title, description }); setEditing(false); setMessage('Enlace actualizado.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo guardar.'); } };
  return <article className="mx-auto mt-5 max-w-3xl"><div className="flex items-start gap-3"><LinkIcon size={36}/><div className="min-w-0 flex-1"><h1 className="text-2xl font-semibold">{resource.title}</h1><a className="block truncate text-sm text-blue-600 underline" href={resource.url ?? '#'} target="_blank" rel="noopener noreferrer">{resource.url}</a></div><Button variant="outline" onClick={() => setEditing(value => !value)}>Editar</Button></div>{resource.previewImageUrl && <img className="mt-5 max-h-72 rounded-md" src={resource.previewImageUrl} alt=""/>}<p className="mt-4">{resource.description || 'Sin descripción.'}</p>{resource.metadataStatus === 'pending' && <p role="status" className="mt-3 text-sm text-outline">Obteniendo metadatos…</p>}{resource.metadataStatus === 'failed' && <div role="alert" className="mt-3"><p>No se pudieron obtener los metadatos. El enlace sigue guardado.</p><Button className="mt-2" variant="outline" disabled={actions.retry.isPending} onClick={async () => { try { await actions.retry.mutateAsync({ id: resource.id }); setMessage('Reintento iniciado.'); } catch { setMessage('No se pudo reintentar.'); } }}>Reintentar metadatos</Button></div>}{editing && <form className="mt-6 rounded-lg bg-surface-variant/55 p-4" onSubmit={save}><label className="block text-sm font-medium">Título<input className="mt-1 w-full rounded-md border-0 bg-surface-variant p-2 focus-visible:outline-2 focus-visible:outline-primary" maxLength={160} value={title} onChange={event => setTitle(event.target.value)}/></label><label className="mt-4 block text-sm font-medium">Descripción<textarea className="mt-1 min-h-28 w-full rounded-md border-0 bg-surface-variant p-2 focus-visible:outline-2 focus-visible:outline-primary" maxLength={1000} value={description} onChange={event => setDescription(event.target.value)}/></label><Button className="mt-3" type="submit" variant="primary" disabled={actions.update.isPending}>Guardar cambios</Button></form>}{message && <p role="status" className="mt-3">{message}</p>}</article>;
}

function NoteEditor({ note, busy, onCancel, onSave }: { note?: Note; busy: boolean; onCancel: () => void; onSave: (input: NoteInput) => Promise<boolean | undefined> }) {
  const [title, setTitle] = useState(note?.title ?? ''); const [description, setDescription] = useState(note?.description ?? ''); const [content, setContent] = useState(note?.currentVersion.content ?? ''); const [message, setMessage] = useState('');
  const [linkQuery, setLinkQuery] = useState(''); const editor = useRef<HTMLTextAreaElement>(null); const matching = useResources({ query: linkQuery.trim() || undefined }, Boolean(linkQuery.trim()));
  const insertLink = (id: string, label: string) => { const position = editor.current?.selectionStart ?? content.length; const link = `[[resource:${id}|${label}]]`; setContent(current => current.slice(0, position) + link + current.slice(position)); setLinkQuery(''); requestAnimationFrame(() => { editor.current?.focus(); editor.current?.setSelectionRange(position + link.length, position + link.length); }); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!title.trim()) { setMessage('El título es obligatorio.'); return; } try { const unchanged = await onSave({ title, description, content }); setMessage(unchanged ? 'El contenido ya estaba actualizado.' : 'Nota guardada.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo guardar. Puedes reintentar.'); } };
  return <form className="mx-auto mt-4 max-w-3xl" onSubmit={submit}><label className="block text-sm font-medium">Título<input className="mt-1 w-full rounded-md border-0 bg-surface-variant p-2 focus-visible:outline-2 focus-visible:outline-primary text-xl" value={title} maxLength={160} onChange={event => setTitle(event.target.value)}/></label><label className="mt-4 block text-sm font-medium">Descripción<input className="mt-1 w-full rounded-md border-0 bg-surface-variant p-2 focus-visible:outline-2 focus-visible:outline-primary" value={description} onChange={event => setDescription(event.target.value)}/></label><label className="mt-4 block text-sm font-medium">Contenido<textarea ref={editor} className="mt-1 min-h-80 w-full rounded-md border-0 bg-surface-variant p-3 focus-visible:outline-2 focus-visible:outline-primary" value={content} onChange={event => setContent(event.target.value)}/></label><div className="mt-2 rounded-lg bg-surface-variant/55 p-3 text-sm"><label className="block">Insertar enlace a un recurso<input className="mt-1 w-full rounded-md border-0 bg-surface-variant p-2 focus-visible:outline-2 focus-visible:outline-primary" value={linkQuery} onChange={event => setLinkQuery(event.target.value)} placeholder="Busca un título o alias" /></label><p className="mt-1 text-xs text-outline">También puedes escribir [[Título]] o [[Título#sección|texto]]. Los enlaces insertados desde el buscador mantienen la identidad aunque cambie el título.</p>{matching.isError && <p role="alert">No se pudo buscar recursos.</p>}{linkQuery.trim() && <ul className="mt-2 max-h-36 overflow-auto">{matching.data?.pages.flatMap(page => page.data).filter(item => item.id !== note?.id).map(item => <li key={item.id}><Button type="button" onClick={() => insertLink(item.id, item.title)}>Insertar {item.title}</Button></li>)}</ul>}</div>{message && <p role="status" className="mt-3 text-sm">{message}</p>}<div className="mt-5 flex gap-2"><Button type="button" onClick={onCancel}>Cancelar</Button><Button type="submit" variant="primary" disabled={busy}>{busy ? 'Guardando…' : 'Guardar'}</Button></div></form>;
}
